# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_Nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_Estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('Es_Nombre', models.CharField(max_length=25)),
                ('Es_Apellido', models.CharField(max_length=25)),
                ('Es_Codigo', models.CharField(max_length=20)),
                ('Es_Venada', models.CharField(choices=[('0', 'Si'), ('1', 'No')], default='0', max_length=1)),
                ('Es_Estado', models.CharField(choices=[('0', 'Activo'), ('1', 'Desactivo')], default='0', max_length=1)),
                ('Es_Departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mun_nombre', models.CharField(max_length=35)),
                ('Mun_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_Programa', models.AutoField(primary_key=True, serialize=False)),
                ('Pr_Nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Es_Municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Es_Departamento', chained_model_field='Es_Departamento', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Municipio'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Es_Programa_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Programa'),
        ),
    ]
