# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Es_Codigo',
            field=models.CharField(max_length=20),
        ),
    ]
