# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Es_Identificacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Es_TipoID',
            field=models.CharField(choices=[('0', 'TI'), ('1', 'CC')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Es_Departamento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Es_Municipio',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='Mun_departamento', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Municipio'),
        ),
    ]
